# Generated by Django 3.2.12 on 2022-02-18 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agent',
            options={'verbose_name': 'エージェント', 'verbose_name_plural': 'エージェント'},
        ),
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': 'プロファイル', 'verbose_name_plural': 'プロファイル'},
        ),
        migrations.AddField(
            model_name='user',
            name='is_agent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='is_organisor',
            field=models.BooleanField(default=True),
        ),
    ]
