# Generated by Django 3.2.12 on 2022-02-25 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20220221_0225'),
    ]

    operations = [
        migrations.AddField(
            model_name='a001',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pictures/'),
        ),
    ]
